---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-folder
  labels:
    app: alpine-folder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-folder
  template:
    metadata:
      labels:
        app: alpine-folder
    spec:
      containers:
      - name: alpine-folder
        image: alpine
        volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
        command: [ "sleep", "1000000" ]
      volumes:
        - name: my-csi-volume
          persistentVolumeClaim:
            claimName: csi-pvc-folder
