---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sharedhostpath-disk
